name: CI

on:
  push:
  pull_request:

jobs:
  test-runner:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y qtbase5-dev qt5-qmake xvfb

      - name: Build project
        run: |
          cd Qt_2
          qmake tictacboom.pro
          make
      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-artifact
          path: Qt_2 # Specify the path to the artifact you want to upload

      
